version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: docker
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    restart: always